# Generated by Django 6.0.1 on 2026-10-02 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntranetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False, help_text='Pode gerenciar contas e editar TODO o conteúdo do site. Vê todos os menus.', verbose_name='Gestor')),
                ('menu_eventos', models.BooleanField(default=True, verbose_name='Menu: Eventos')),
                ('menu_tarefas', models.BooleanField(default=True, verbose_name='Menu: Tarefas')),
                ('menu_calendario', models.BooleanField(default=True, verbose_name='Menu: Calendário')),
                ('menu_equipe', models.BooleanField(default=False, verbose_name='Menu: Equipe')),
                ('content_projetos', models.BooleanField(default=False, verbose_name='Conteúdo: Projetos')),
                ('content_colecoes', models.BooleanField(default=False, verbose_name='Conteúdo: Coleções')),
                ('content_visitas3d', models.BooleanField(default=False, verbose_name='Conteúdo: Visitas 3D')),
                ('content_slides', models.BooleanField(default=False, verbose_name='Conteúdo: Slides')),
                ('content_publicacoes', models.BooleanField(default=False, verbose_name='Conteúdo: Publicações')),
                ('content_equipe', models.BooleanField(default=False, verbose_name='Conteúdo: Equipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intranet_access', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso à intranet',
                'verbose_name_plural': 'Acessos à intranet',
            },
        ),
    ]
