# Generated by Django 5.2.9 on 2025-12-20 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Nome do Projeto"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug (URL)")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Localização"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Imagem de Capa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="slides/", verbose_name="Imagem"),
                ),
                ("link", models.URLField(blank=True, verbose_name="Link (Opcional)")),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Slide (Carousel)",
                "verbose_name_plural": "Slides (Carousel)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Nome do Artefato"),
                ),
                ("description", models.TextField(verbose_name="Descrição do Artefato")),
                (
                    "image",
                    models.ImageField(
                        upload_to="artifacts/", verbose_name="Imagem do Artefato"
                    ),
                ),
                (
                    "sketchfab_embed",
                    models.TextField(
                        blank=True,
                        help_text="Cole o código iframe do Sketchfab aqui.",
                        verbose_name="Embed 3D (Sketchfab)",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="core.project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artefato",
                "verbose_name_plural": "Artefatos",
            },
        ),
    ]
