# Generated by Django 5.2.9 on 2025-12-21 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="artifact",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="artifacts/"),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="sketchfab_embed",
            field=models.TextField(
                blank=True, help_text="Cole o código do iframe do Sketchfab aqui"
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("cover_image", models.ImageField(upload_to="collections/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="collections", to="core.project"
                    ),
                ),
            ],
        ),
    ]
