# Generated by Django 5.2.9 on 2025-12-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_artifact_created_at_alter_artifact_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="collections", to="core.project"
            ),
        ),
        migrations.CreateModel(
            name="CollectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="collections/gallery/")),
                ("order", models.IntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
