# Generated by Django 5.2.9 on 2025-12-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_collection_projects_collectionimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="model_file",
            field=models.FileField(
                blank=True,
                help_text="Upload de arquivo 3D (GLB, GLTF, USDZ)",
                null=True,
                upload_to="artifacts/models/",
            ),
        ),
    ]
