# Generated by Django 5.2.9 on 2025-12-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_artifact_model_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="annotations",
            field=models.TextField(
                blank=True,
                help_text="Anotações sobre o modelo 3D (opcional) - informações técnicas, descobertas, etc.",
            ),
        ),
    ]
