# Generated by Django 5.2.9 on 2025-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_artifact_annotations"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Sobre o LAPOMED", max_length=200, verbose_name="Título"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Texto sobre o laboratório", verbose_name="Conteúdo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="about/", verbose_name="Imagem"
                    ),
                ),
                ("mission", models.TextField(blank=True, verbose_name="Missão")),
                ("vision", models.TextField(blank=True, verbose_name="Visão")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Seção Sobre",
                "verbose_name_plural": "Seções Sobre",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrição da Parceria"),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="partnerships/", verbose_name="Logo"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Parceria",
                "verbose_name_plural": "Parcerias",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 🏺 ou fa-flask",
                        max_length=50,
                        verbose_name="Ícone (emoji ou classe CSS)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Área de Pesquisa",
                "verbose_name_plural": "Áreas de Pesquisa",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("role", models.CharField(max_length=200, verbose_name="Cargo/Função")),
                ("bio", models.TextField(verbose_name="Biografia")),
                ("photo", models.ImageField(upload_to="team/", verbose_name="Foto")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "lattes",
                    models.URLField(blank=True, verbose_name="Currículo Lattes"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Membro da Equipe",
                "verbose_name_plural": "Membros da Equipe",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Ano")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="timeline/",
                        verbose_name="Imagem",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Marco Histórico",
                "verbose_name_plural": "Linha do Tempo",
                "ordering": ["-year"],
            },
        ),
    ]
