# Generated by Django 5.2.9 on 2025-12-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_aboutsection_partnership_researcharea_teammember_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutsection",
            options={
                "ordering": ["order"],
                "verbose_name": "👥 Quem Somos - Seção Sobre",
                "verbose_name_plural": "👥 Quem Somos - Seções Sobre",
            },
        ),
        migrations.AlterModelOptions(
            name="artifact",
            options={
                "verbose_name": "🏛️ Projetos - Artefato",
                "verbose_name_plural": "🏛️ Projetos - Artefatos",
            },
        ),
        migrations.AlterModelOptions(
            name="partnership",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "👥 Quem Somos - Parceria",
                "verbose_name_plural": "👥 Quem Somos - Parcerias",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "verbose_name": "🏛️ Projetos - Projeto",
                "verbose_name_plural": "🏛️ Projetos - Projetos",
            },
        ),
        migrations.AlterModelOptions(
            name="researcharea",
            options={
                "ordering": ["order"],
                "verbose_name": "👥 Quem Somos - Área de Pesquisa",
                "verbose_name_plural": "👥 Quem Somos - Áreas de Pesquisa",
            },
        ),
        migrations.AlterModelOptions(
            name="slide",
            options={
                "ordering": ["order"],
                "verbose_name": "🏠 Home - Slide do Carousel",
                "verbose_name_plural": "🏠 Home - Slides do Carousel",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "👥 Quem Somos - Membro da Equipe",
                "verbose_name_plural": "👥 Quem Somos - Equipe",
            },
        ),
        migrations.AlterModelOptions(
            name="timeline",
            options={
                "ordering": ["-year"],
                "verbose_name": "👥 Quem Somos - Marco Histórico",
                "verbose_name_plural": "👥 Quem Somos - Linha do Tempo",
            },
        ),
    ]
