# Generated by Django 5.2.9 on 2025-12-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_aboutsection_options_alter_artifact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutsection",
            name="values",
            field=models.TextField(blank=True, verbose_name="Valores"),
        ),
    ]
