# Generated by Django 6.0.1 on 2026-05-13 11:24

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_navitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="LcpPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="LCP — Levantine Ceramics Project",
                        max_length=200,
                        verbose_name="Título do Hero",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True,
                        default="Parceria internacional",
                        max_length=300,
                        verbose_name="Subtítulo do Hero",
                    ),
                ),
                (
                    "logo_lcp",
                    models.ImageField(
                        blank=True,
                        help_text="Opcional. Se vazio, um placeholder será exibido.",
                        null=True,
                        upload_to="lcp/",
                        verbose_name="Logo do LCP",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="2-3 parágrafos sobre a parceria com o LCP.",
                        verbose_name="Conteúdo da página",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        default="https://www.levantineceramics.org",
                        verbose_name="URL da plataforma LCP",
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        default="Acessar a plataforma LCP",
                        max_length=80,
                        verbose_name="Texto do botão",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Quando desativado, a página retorna 404 e o item LCP some do menu.",
                        verbose_name="Ativo",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "🏺 LCP - Página",
                "verbose_name_plural": "🏺 LCP - Página",
            },
        ),
        migrations.AddField(
            model_name="navitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Defina apenas para itens do tipo 'Sub-item de dropdown'.",
                limit_choices_to={"kind": "social"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.navitem",
                verbose_name="Pai (apenas para Sub-itens)",
            ),
        ),
        migrations.AlterField(
            model_name="navitem",
            name="custom_url",
            field=models.CharField(
                blank=True,
                help_text="Use apenas com tipo 'Custom' ou 'Sub-item'. Ex: /contato/ ou https://exemplo.com",
                max_length=400,
                verbose_name="URL custom",
            ),
        ),
        migrations.AlterField(
            model_name="navitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("projects", "Projetos"),
                    ("about", "Quem Somos"),
                    ("publications", "Publicações"),
                    ("learning_hub", "Hub de Aprendizado"),
                    ("collections", "Coleções Digitais (dropdown)"),
                    ("virtual_tours", "Visitas Virtuais 3D"),
                    ("coalitvs", "COALITVS"),
                    ("lcp", "LCP — Levantine Ceramics Project"),
                    ("social", "Notícias / Redes (dropdown)"),
                    ("sublink", "Sub-item de dropdown"),
                    ("contact", "Contato"),
                    ("custom", "Custom (URL livre)"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="virtualtour",
            name="embed_url",
            field=models.URLField(
                blank=True,
                help_text="Cole a URL do tour (Sketchfab, Matterport, Kuula etc.). Para Sketchfab, tanto a URL da página do modelo (https://sketchfab.com/3d-models/...) quanto a URL de embed (.../embed) funcionam — convertemos automaticamente.",
                verbose_name="URL Embed",
            ),
        ),
    ]
