# Generated by Django 6.0.1 on 2026-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_coalitvs_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='kind',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projetos'), ('about', 'Quem Somos'), ('team', 'Equipe'), ('publications', 'Publicações'), ('learning_hub', 'Hub de Aprendizado'), ('collections', 'Coleções Digitais (dropdown)'), ('virtual_tours', 'Visitas Virtuais 3D'), ('coalitvs', 'COALITVS'), ('lcp', 'LCP — Levantine Ceramics Project'), ('social', 'Notícias / Redes (dropdown)'), ('sublink', 'Sub-item de dropdown'), ('contact', 'Contato'), ('custom', 'Custom (URL livre)')], max_length=20, verbose_name='Tipo'),
        ),
    ]
