# Generated by Django 6.0.1 on 2026-07-17 00:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_team_navitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='explore_url',
            field=models.URLField(blank=True, help_text="URL de destino do botão 'Explorar' no card/modal. Se vazio, usa a página da categoria. Ex: https://lapomed.com.br/colecoes/edificacoes/", verbose_name='Link do botão Explorar'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Descrição'),
        ),
    ]
