# Generated by Django 6.0.1 on 2026-07-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_collection_explore_url_alter_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcppage',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='Opcional. Imagem de fundo atrás do título. Se vazio, usa o gradiente escuro padrão.', null=True, upload_to='lcp/', verbose_name='Imagem de fundo do Hero'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='explore_url',
            field=models.URLField(blank=True, help_text="URL de destino do botão 'Explorar' no modal (ex: modelo 3D, página do projeto, tour 3D das Visitas 3D). Se vazio, o botão Explorar não aparece.", verbose_name='Link do botão Explorar'),
        ),
    ]
