# Generated by Django 6.0.1 on 2026-07-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_collection_explore_url_alter_collection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Laboratório de Arqueologia — LAPOMED-USP', help_text='Nome em destaque no topo da página (ex.: Laboratório de Arqueologia — LAPOMED-USP).', max_length=200, verbose_name='Nome da instituição')),
                ('department', models.TextField(blank=True, help_text='Uma linha por informação (ex.: Museu de Arqueologia e Etnologia — MAE / Universidade de São Paulo). Cada quebra de linha vira uma linha na página.', verbose_name='Departamento / Afiliação')),
                ('address', models.TextField(blank=True, help_text='Logradouro, número, complemento, bairro, cidade/UF.', verbose_name='Endereço')),
                ('postal_code', models.CharField(blank=True, help_text='Ex.: 05508-070', max_length=20, verbose_name='CEP')),
                ('phone', models.CharField(blank=True, help_text='Formato de exibição (ex.: (11) 3091-0000).', max_length=40, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Número de exibição (ex.: (11) 90000-0000). O link é gerado só com os dígitos.', max_length=40, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='lapomed@lapomed.usp.br', help_text='E-mail de contato exibido com link mailto.', max_length=254, verbose_name='E-mail')),
                ('maps_embed_url', models.URLField(blank=True, help_text='URL do atributo src do iframe do Google Maps (Compartilhar → Incorporar um mapa → copie o valor de src="...").', max_length=600, verbose_name='URL do mapa (embed)')),
                ('maps_directions_url', models.URLField(blank=True, help_text="Link do Google Maps para o botão 'Como chegar' (ex.: https://maps.app.goo.gl/...).", max_length=600, verbose_name="URL 'Como chegar'")),
                ('active', models.BooleanField(default=True, help_text='Quando desativado, a página de contato usa placeholders vazios.', verbose_name='Ativo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '📞 Contato - Informações',
                'verbose_name_plural': '📞 Contato - Informações',
            },
        ),
    ]
