# Generated by Django 6.0.1 on 2026-07-23 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_contactinfo'),
        ('core', '0032_lcppage_hero_bg_image_alter_collection_explore_url'),
    ]

    operations = [
    ]
