# Generated by Django 6.0.1 on 2026-10-01 21:26

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20260722_2139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Vincula este membro a uma conta de login da intranet (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da intranet'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='kind',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projetos'), ('about', 'Quem Somos'), ('team', 'Equipe'), ('publications', 'Publicações'), ('learning_hub', 'Hub de Aprendizado'), ('collections', 'Coleções Digitais (dropdown)'), ('virtual_tours', 'Visitas Virtuais 3D'), ('events', 'Eventos'), ('coalitvs', 'COALITVS'), ('lcp', 'LCP — Levantine Ceramics Project'), ('social', 'Notícias / Redes (dropdown)'), ('sublink', 'Sub-item de dropdown'), ('contact', 'Contato'), ('custom', 'Custom (URL livre)')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug (URL)')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Descrição')),
                ('start_at', models.DateTimeField(verbose_name='Início')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Local')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagem de capa')),
                ('registration_url', models.URLField(blank=True, verbose_name='Link de inscrição')),
                ('category', models.CharField(choices=[('palestra', 'Palestra'), ('workshop', 'Workshop / Minicurso'), ('defesa', 'Defesa / Qualificação'), ('exposicao', 'Exposição'), ('congresso', 'Congresso / Simpósio'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('published', models.BooleanField(default=False, help_text='Quando marcado, o evento aparece na página pública /eventos/.', verbose_name='Publicado no site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📅 Eventos - Evento',
                'verbose_name_plural': '📅 Eventos - Eventos',
                'ordering': ['-start_at'],
            },
        ),
    ]
