"""
Django settings for lapomed_gallery project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Adiciona o diretório raiz ao path para importar o config
sys.path.insert(0, str(BASE_DIR))

# Importa configurações centralizadas
from config import SECRET_KEY, DEBUG, ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS, DATABASES

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "tailwind",
    "lapomed",
    "django_browser_reload",
    "tinymce",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

X_FRAME_OPTIONS = "SAMEORIGIN"

TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    "menubar": "edit view insert format tools",
    "plugins": (
        "advlist autolink lists link image charmap preview anchor "
        "searchreplace visualblocks code fullscreen "
        "insertdatetime media table help wordcount paste"
    ),
    "toolbar": (
        "undo redo | blocks | bold italic underline | "
        "alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | link image | removeformat | code | help"
    ),
    # Upload de imagens — endpoint protegido por staff_member_required
    "images_upload_url": "/rich-text/upload/",
    "images_upload_credentials": True,
    "automatic_uploads": True,
    "file_picker_types": "image",
    # Esconde do menu Format os submenus que permitiriam trocar fonte/tamanho/cor
    "removed_menuitems": "fontfamily fontsize forecolor backcolor",
    "language": "pt_BR",
    "branding": False,
    "promotion": False,
    # Forca a fonte do site (Lato) dentro do iframe do editor para que o autor
    # ja escreva no visual final
    "content_style": (
        "@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap');"
        "body{font-family:'Lato',sans-serif;font-size:16px;line-height:1.6;color:#374151}"
        "h1,h2,h3,h4{font-family:'Lato',sans-serif;color:#111827}"
    ),
    # Mesmo se o usuario forcar via algum atalho, oferecer apenas Lato
    "font_family_formats": "Lato=Lato,sans-serif",
    "font_size_formats": "14px 16px 18px 20px 24px",
    # Limpa estilos inline indesejados ao colar de Word/PDF/sites externos
    # para nao herdar fontes/tamanhos que quebram o layout do site
    "paste_as_text": False,
    "paste_remove_styles_if_webkit": True,
    "paste_webkit_styles": "none",
    "paste_merge_formats": True,
    "invalid_styles": {
        "*": "font-family font-size font color background-color line-height letter-spacing"
    },
    "valid_styles": {
        "*": "text-align"
    },
}

ROOT_URLCONF = "lapomed_gallery.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lapomed_gallery.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Configuração suporta PostgreSQL via DATABASE_URL e SQLite local (importado do config)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Configuração para servir arquivos estáticos em produção com WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Upload — TinyMCE pode enviar imagens grandes coladas/arrastadas (base64 -> file)
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024

# Tailwind Configuration
TAILWIND_APP_NAME = 'lapomed'

INTERNAL_IPS = [
    "127.0.0.1",
]

NPM_BIN_PATH = "npm.cmd"

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "LAPOMED Admin",
    "site_header": "LAPOMED",
    "site_brand": "LAPOMED",
    "site_logo": None,
    "login_logo": None,
    "welcome_sign": "Bem-vindo ao Painel Administrativo LAPOMED",
    "copyright": "LAPOMED USP",
    "search_model": ["core.Project"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Site", "url": "home", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Customização de ícones
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Core
        "core": "fas fa-home",
        "core.Slide": "fas fa-images",
        "core.Project": "fas fa-project-diagram",
        "core.Artifact": "fas fa-monument",
        "core.Collection": "fas fa-folder-open",
        
        # Quem Somos
        "core.AboutSection": "fas fa-info-circle",
        "core.TeamMember": "fas fa-user-tie",
        "core.Timeline": "fas fa-history",
        "core.ResearchArea": "fas fa-microscope",
        "core.Partnership": "fas fa-handshake",
    },
    
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}



